name = "lol-stats"
main = "worker.js"  # ğŸ‘ˆ å…³é”®ï¼è¿™é‡Œå†™ä»€ä¹ˆï¼Œä½ çš„JSæ–‡ä»¶å°±å¾—å«ä»€ä¹ˆ
compatibility_date = "2026-02-03"

[[kv_namespaces]]
binding = "LOL_KV"
id = "c96e310d082645b8a8fe254db1c3bc92"
